# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 326f66a42557020a1c2ba766f7ab5b9136ed7ffbe488685ec736112062fbe75b908840ae95ea3c1246a5bf5998fd6b4cdf354cfe9e8cb3b7f0040bdd1b553c3c

test:
  secret_key_base: b02dba73e4317fd2527ed6e1a66339b354d4a54e8138cffc3415a6e5fe86205a4651b3c35b094d0e28a47f8eb76170c33fec3b3328c24df5ac267e684c392e83

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
